[package]
name = "rust"
version = "0.1.0"
edition = "2021"
authors = ["blackshadowsoftwareltd@gmail.com"]

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
